name: love_story_unicorn
description: "A new Flutter project."

publish_to: 'none'

version: 3.0.4+27

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Utils:
  dropdown_button2: 2.3.9
  google_fonts: 6.2.1
  logger: 2.5.0
  intl: 0.19.0
  table_calendar: 3.1.3
  toastification: 2.3.0
  shared_preferences: 2.3.3


  # Fetch server data & State management :
  get_it: 8.0.3
  get: 4.6.6
  http: 1.2.2
  json_annotation: 4.9.0
  internet_connection_checker_plus: 2.5.2
  connectivity_plus: 6.1.1
  device_info_plus: 11.2.0

  # Image & video view:
  flutter_svg: 2.0.16
  image_picker: 1.1.2
  camera: 0.11.0+2
  cached_network_image: 3.4.1
  shimmer: 3.0.0
  video_player: 2.9.2
  lottie: 3.1.3
  path_provider: 2.1.5
  swipable_stack: 2.0.0
  permission_handler: 11.3.1
  flutter_image_compress: 2.3.0
  video_compress: 3.1.3
  photo_view: 0.15.0

  # Firebase:
  firebase_core: 3.8.1
  firebase_auth: 5.3.4
  cloud_firestore: 5.5.1
  firebase_storage: 12.3.7
  firebase_remote_config: 5.2.0
  flutter_local_notifications: 17.2.2
  firebase_messaging: 15.1.6
  googleapis_auth: 1.6.0

  # Subscription:
  in_app_purchase: 3.2.0
  in_app_purchase_android: 0.3.6+12
  in_app_purchase_storekit: 0.3.20+2

  # Custom package :
  flutter_typeahead:
    path: flutter_typeahead

  cupertino_icons: 1.0.8
  carousel_slider: 5.0.0

  # Chat bubbles:
  chat_bubbles: 1.6.0

  # URL Launch
  url_launcher: 6.3.1
  webview_flutter: 4.10.0

  #audio
  on_audio_query: 2.9.0
  just_audio: 0.9.42
  audio_waveforms: 1.2.0

  #package_info_plus:
  package_info_plus: 8.1.2



dev_dependencies:
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter

  # Model management :
  json_serializable: 6.9.0

  # Utils:
  lint: 2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/animations/
    - config/service_account.json
